---
swagger: "2.0"
info:
  description: "This is a simple API for get status for the bathroom app"
  version: "1.1"
  title: "Simple Bathroom Status"
  contact:
    email: "admin@onedaywillwillownbathroomapp.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/drumadrian/bathroom-app-get-status/1.0.0"
tags:
- name: "admins"
  description: "none"
- name: "developers"
  description: "none"
schemes:
- "https"
paths:
  /getstatus/{unique_id}:
    get:
      tags:
      - "developers"
      summary: "gets status of a bathroom  or multiple  bathrooms"
      description: "By passing nothing, you will get all of the bathrooms and statuses\n"
      operationId: "getallstatuses"
      produces:
      - "application/json"
      parameters:
      - name: "unique_id"
        in: "path"
        description: "pass DynamoDB Primary partition key to get an entry"
        required: true
        type: "string"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/InventoryItem"
        400:
          description: "bad input parameter"
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:101845606311:function:getallstatuses/invocations"
        responses:
          default:
            statusCode: "200"
        type: "aws"
        parameters:
          unique-id: "$input.params('unique_id')"
        requestTemplates:
          application/json: "{\n  \"unique_id\" : \"$input.params('unique_id')\"\n\
            }"
definitions:
  InventoryItem:
    type: "object"
    required:
    - "id"
    - "manufacturer"
    - "name"
    - "releaseDate"
    properties:
      id:
        type: "string"
        format: "uuid"
      name:
        type: "string"
      releaseDate:
        type: "string"
        format: "int32"
      manufacturer:
        $ref: "#/definitions/Manufacturer"
  Manufacturer:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
      homePage:
        type: "string"
        format: "url"
      phone:
        type: "string"
x-aws-api-id: "6j2lxzffih"
